### ISSUE TITLE
[Feature] Chiseling bones into Bone Shards.

### ISSUE THREAD

**Issue by evilgenious448** [guillaume009/runelite-plugin-action-progress#56]
A the title suggests, could you please add the action progress for chiseling bones into bone shards. This applies to all blessed bones that can be chiseled into bone shards. 
Link to Wiki page for all variations:
https://oldschool.runescape.wiki/w/Blessed_bone_shards

Thank you :)

**Comment by guillaume009** [comment]
Haven't been to Varlamore yet. Once I do, I'll look into this

**Comment by guillaume009** [comment]
Yes, it is!

**Comment by guillaume009** [comment]
Pushed bd2b6973bd6af7873dde6b169bfd9b112baaa9a5 to implement this

**Comment by evilgenious448** [comment]
Thank you so much @guillaume009 and @druyang.

Would it be possible to make one additional request please. Could you also implement an action timer for adding Sunfire Splinters (with pestle and mortar in inventory) to the Jug of Wine to create Jug of Sunfire Wine. 

https://oldschool.runescape.wiki/w/Jug_of_sunfire_wine

**Comment by guillaume009** [comment]
For sure. I just don't have sunfire splinters to try out the change. Should be straight forward but I would like to test it before publishing the change.

If you @evilgenious448 are a dev and would be able to run a dev build we can try it out together. Add me on discord "Krytlex". Otherwise if @druyang want to take this one, go for it
